app/home/forms.py
# _*_ coding: utf-8 _*_
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, Email, Regexp, EqualTo, ValidationError
from app.models import User

class RegisterForm(FlaskForm):
    """
    用户注册表单
    """
    username = StringField(
        validators=[
            DataRequired("用户名不能为空！"),
        ],
        description="用户名",
        render_kw={
            "placeholder": "请输入用户名！",
        }
    )
    email = StringField(
        validators=[
            DataRequired("邮箱不能为空！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "type": "email",
            "placeholder": "请输入邮箱！",
        }
    )
    pwd = PasswordField(
        validators=[
            DataRequired("密码不能为空！")
        ],
        description="密码",
        render_kw={
            "placeholder": "请输入密码！",
        }
    )
    repwd = PasswordField(
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo('pwd', message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "placeholder": "请输入确认密码！",
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-primary",
        }
    )

    def validate_email(self, field):
        """
        检测注册邮箱是否已经存在
        :param field: 字段名
        """
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")

class LoginForm(FlaskForm):
    """
    登录功能
    """
    email = StringField(
        validators=[
            DataRequired("邮箱不能为空！")
        ],
        description="邮箱",
        render_kw={
            "type"       : "email",
            "placeholder": "请输入邮箱！",
        }
    )
    pwd = PasswordField(

        validators=[
            DataRequired("密码不能为空！")
        ],
        description="密码",
        render_kw={
            "type"       : "password",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-primary",
        }
    )

class SuggetionForm(FlaskForm):
    """
    意见建议
    """
    name = StringField(
        label="姓名",
        validators=[
            DataRequired("姓名不能为空！")
        ],
        description="姓名",
        render_kw={
            "placeholder": "请输入姓名！",
            "class" : "form-control"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("邮箱不能为空！")
        ],
        description="邮箱",
        render_kw={
            "type"       : "email",
            "placeholder": "请输入邮箱！",
            "class" : "form-control"
        }
    )
    content = TextAreaField(
        label="意见建议",
        validators=[
            DataRequired("内容不能为空！")
        ],
        description="意见建议",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入内容！",
            "rows" : 7
        }
    )
    submit = SubmitField(
        '发送消息',
        render_kw={
            "class": "btn-default btn-cf-submit",
        }
    )

app/home/__init__.py
# _*_ coding:utf-8 _*_

from flask import Blueprint

home = Blueprint("home",__name__)

import app.home.views

app/home/views.py
# _*_ coding: utf-8 _*_
from . import home
from app import db
from app.home.forms import LoginForm,RegisterForm,SuggetionForm
from app.models import User ,Area,Scenic,Travels,Collect,Suggestion,Userlog
from flask import render_template, url_for, redirect, flash, session, request
from werkzeug.security import generate_password_hash
from sqlalchemy import and_
from functools import wraps

def user_login(f):
    """
    登录装饰器
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("home.login"))
        return f(*args, **kwargs)

    return decorated_function

@home.route("/login/", methods=["GET", "POST"])
def login():
    """
    登录
    """
    form = LoginForm()              # 实例化LoginForm类
    if form.validate_on_submit():   # 如果提交
        data = form.data            # 接收表单数据
        # 判断用户名和密码是否匹配
        user = User.query.filter_by(email=data["email"]).first()    # 获取用户信息
        if not user :
            flash("邮箱不存在！", "err")           # 输出错误信息
            return redirect(url_for("home.login")) # 调回登录页
        if not user.check_pwd(data["pwd"]):     # 调用check_pwd()方法，检测用户名密码是否匹配
            flash("密码错误！", "err")           # 输出错误信息
            return redirect(url_for("home.login")) # 调回登录页

        session["user_id"] = user.id                # 将user_id写入session, 后面用户判断用户是否登录
        # 将用户登录信息写入Userlog表
        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog) # 存入数据
        db.session.commit()     # 提交数据
        return redirect(url_for("home.index")) # 登录成功，跳转到首页
    return render_template("home/login.html", form=form) # 渲染登录页面模板

@home.route("/register/", methods=["GET", "POST"])
def register():
    """
    注册功能
    """
    form = RegisterForm()           # 导入注册表单
    if form.validate_on_submit():   # 提交注册表单
        data = form.data            # 接收表单数据
        # 为User类属性赋值
        user = User(
            username = data["username"],            # 用户名
            email = data["email"],                  # 邮箱
            pwd = generate_password_hash(data["pwd"]),# 对密码加密
        )
        db.session.add(user) # 添加数据
        db.session.commit()  # 提交数据
        flash("注册成功！", "ok") # 使用flask存储成功信息
    return render_template("home/register.html", form=form) # 渲染模板

@home.route("/logout/")
def logout():
    """
    退出登录
    """
    # 重定向到home模块下的登录。
    session.pop("user_id", None)
    return redirect(url_for('home.login'))    


@home.route("/")
def index():
    """
    首页
    """
    area = Area.query.all() # 获取所有城市
    hot_area = Area.query.filter_by(is_recommended = 1).limit(2).all() # 获取热门城市
    scenic = Scenic.query.filter_by(is_hot = 1).all() # 热门景区
    return render_template('home/index.html',area=area,hot_area=hot_area,scenic=scenic) # 渲染模板

@home.route("/info/<int:id>/")
def info(id=None):  # id 为景区ID
    """
    详情页
    """
    scenic = Scenic.query.get_or_404(int(id)) # 根据景区ID获取景区数据，如果不存在返回404
    user_id = session.get('user_id',None)    # 获取用户ID,判断用户是否登录
    if user_id :                              # 如果已经登录
        count = Collect.query.filter_by(      # 根据用户ID和景区ID判断用户是否已经收藏该景区
            user_id =int(user_id),
            scenic_id=int(id)
        ).count()
    else :                                    # 用户未登录状态
        user_id = 0
        count = 0    
    return render_template('home/info.html',scenic=scenic,user_id=user_id,count=count)   # 渲染模板

@home.route("/about/")
def about():
    """
    关于我们
    """
    return render_template('home/about.html')

@home.route("/contact/",methods=["GET", "POST"])
def contact():

    """
    联系我们
    """
    form = SuggetionForm()              # 实例化SuggestionForm类
    if form.validate_on_submit():       # 判断用户是否提交表单
        data = form.data                # 接收用户提交的数据
        # 为属性赋值
        suggestion = Suggestion(
            name = data["name"],
            email=data["email"],
            content = data["content"],
        )
        db.session.add(suggestion)       # 添加数据
        db.session.commit()              # 提交数据
        flash("发送成功！", "ok")        # 用flask存储发送成功消息
        form.content.data = ''           # 设置内容为空
    return render_template('home/contact.html',form=form) # 渲染模板，并传递表单数据


@home.route("/search/")
def search():
    """
    搜素功能
    """
    page = request.args.get('page', 1, type=int) # 获取page参数值 
    area = Area.query.all()    # 获取所有城市
    area_id = request.args.get('area_id',type=int)  # 地区
    star = request.args.get('star',type=int)        # 星级

    if area_id or star :    # 根据星级搜索景区
        filters = and_(Scenic.area_id==area_id,Scenic.star==star)
        page_data = Scenic.query.filter(filters).paginate(page=page, per_page=6)
    else :                  # 搜索全部景区    
        page_data = Scenic.query.paginate(page=page, per_page=3)
    return render_template('home/search.html',page_data=page_data,area=area,area_id=area_id,star=star)

'''
游记
'''
@home.route("/travels/<int:id>/")
def travels(id=None):
    """
    详情页
    """
    travels = Travels.query.get_or_404(int(id))
    return render_template('home/travels.html',travels=travels) 


'''
景区相关
'''
@home.route("/collect_add/")
@user_login
def collect_add():
    """
    收藏景区
    """
    scenic_id = request.args.get("scenic_id", "")  # 接收传递的参数scenic_id
    user_id   = session['user_id']                  # 获取当前用户的ID
    collect = Collect.query.filter_by(              # 根据用户ID和景区ID判断是否该收藏
        user_id =int(user_id),
        scenic_id=int(scenic_id)
    ).count()
    # 已收藏
    if collect == 1:
        data = dict(ok=0)     # 写入字典
    # 未收藏进行收藏
    if collect == 0:
        collect = Collect(
            user_id =int(user_id),
            scenic_id=int(scenic_id)
        )
        db.session.add(collect)  # 添加数据
        db.session.commit()      # 提交数据
        data = dict(ok=1)        # 写入字典
    import json                 # 导入模块
    return json.dumps(data)     # 返回json数据

@home.route("/collect_cancel/")
@user_login
def collect_cancel():
    """
    收藏景区
    """
    id = request.args.get("id", "")    # 获取景区ID
    user_id = session["user_id"]       # 获取当前用户ID
    collect = Collect.query.filter_by(id=id,user_id=user_id).first() # 查找Collect表，查看记录是否存在
    if collect :                      # 如果存在
        db.session.delete(collect)     # 删除数据
        db.session.commit()             # 提交数据
        data = dict(ok=1)               # 写入字典
    else :
        data = dict(ok=-1)           # 写入字典
    import json                     # 引入json模块
    return json.dumps(data)         # 输出json格式


@home.route("/collect_list/")
@user_login
def collect_list():
    page = request.args.get('page', 1, type=int) # 获取page参数值
    # 根据user_id删选Collect表数据
    page_data = Collect.query.filter_by(user_id = session['user_id']).order_by(
        Collect.addtime.desc()
    ).paginate(page=page, per_page=3)                                     # 使用分页方法
    return render_template('home/collect_list.html',page_data=page_data) # 渲染模板

app/templates/home/about.html
{% extends "home/home.html" %}

{% block content %}

<div id="why1">
  <div class="container">

    <h2 class="animated">为什么选择我们</h2>

    <div class="title1 animated">因为专注，所以专业。<br>专注旅游，我们是认真的！</div>
    <br><br>

    <div class="row">
      <div class="col-sm-3">
        <div class="thumb2 animated">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="{{ url_for('static',filename='base/images/why1.png') }}" alt="" class="img1 img-responsive">
                <img src="{{ url_for('static',filename='base/images/why1_hover.png') }}" alt="" class="img2 img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">神奇的旅行</div>
                <div class="txt2">为您展示真实的旅游景区、精彩的旅游照片、全面的旅游攻略以及最新的旅游资讯</div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="thumb2 animated">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="{{ url_for('static',filename='base/images/why2.png') }}" alt="" class="img1 img-responsive">
                <img src="{{ url_for('static',filename='base/images/why2_hover.png') }}" alt="" class="img2 img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">分享旅行</div>
                <div class="txt2">交换资讯，分享旅行。帮助这里的这里朋友，或者是获得帮助。也可以交流攻略、美食、音乐、摄影日记，以及与旅行有关的零零种种...</div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="thumb2 animated">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="{{ url_for('static',filename='base/images/why3.png') }}" alt="" class="img1 img-responsive">
                <img src="{{ url_for('static',filename='base/images/why3_hover.png') }}" alt="" class="img2 img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">发现惊喜</div>
                <div class="txt2">只要你爱旅行，只要你有爱。这里的一切都是都由你和其他成员产生和决定。</div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="thumb2 animated">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="{{ url_for('static',filename='base/images/why4.png') }}" alt="" class="img1 img-responsive">
                <img src="{{ url_for('static',filename='base/images/why4_hover.png') }}" alt="" class="img2 img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">优质的服务</div>
                <div class="txt2">我们是一个高质量的旅游爱好者群体，钟情于自驾游，拥有专业的摄影技术，为您提供最优质的旅游服务。</div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="company1">
  <div class="container">

    <h2 class="animated">关于本项目</h2>
    <div style="padding: 30px">
      <div class="title1 animated">
        当前项目参考网络上的一些资料，仅用于毕业设计，不做与商业用途，限于开发能力，网站并不完善，望见谅
      </div>
    </div>

  </div>
</div>

{% endblock %}

app/templates/home/collect_list.html
{% extends "home/home.html" %}
{% import "common/home_page.html" as pg %}
{% block content %}
<div id="main">
<div id="content">
  <div class="container">
    <div class="tabs_wrapper tabs1_wrapper">
      <div class="tabs tabs2">
        <div class="tabs_content tabs1_content">
            <div id="tabs-1">
              <div style="background: #fafafa;padding: 20px;border-bottom: 3px solid #1cbbb4;">
                全部收藏
              </div>
              <div class="row">
                <div class="col-sm-12">
                  {% if not page_data.items %}
                    <div class="txt1" style="padding: 20px">暂时没有收藏景区！</div>
                  {% else %}
                  <div class="row">
                    {% for v in page_data.items %}
                    <div class="col-sm-4">
                      <div class="thumb4">
                        <div class="thumbnail clearfix">
                          <figure>
                            <a href="{{url_for('home.info',id=v.scenic.id)}}">
                            <img src="{{url_for('static',filename='uploads/'+ v.scenic.logo)}}" height='240px' class="img-responsive">
                            </a>
                          </figure>    
                          <div class="caption">
                            <div class="txt1">{{ v.scenic.title }}</div>
                            <div class="txt3 clearfix">
                              <div class="left_side">
                                <div class="nums">{{ v.scenic.address }}</div>
                              </div>
                              <div class="right_side"><a href="javascript:;" class="collect-cancle btn-default btn1" value={{v.id}}>取消收藏</a></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    {% if page_data.items %}
    <div class="page" style="text-align: center;">
      {{ pg.page(page_data,'home.collect_list') }}
    </div>
    {% endif %}
  </div>
</div>
<script src="{{ url_for('static',filename='layer/layer.js') }}"></script>
<script>
    $(document).ready(function () {
        $(".collect-cancle").click(function () {  // 触发点击事件
            var id = $(this).attr("value");   // 获取收藏ID
            $.ajax({
                url: "{{ url_for('home.collect_cancel') }}", // 提交URL
                type: "GET",         // 提交方式为GET
                data:{id: id},       // 传递参数
                dataType: "json",    // 设置数据类型为json
                success: function (res) {  // 操作成功执行语句
                    if (res.ok == 1) {
                        layer.msg("取消收藏！",{icon:1,time:1000},function(){   // 弹出提示信息
                          window.location.reload(); // 重新加载页面
                        });
                    } else {
                        layer.msg("取消收藏失败！",{icon:2,time:2000}); // 弹出提示信息
                    }
                }
            })
        });
    });
</script>
{% endblock %}

app/templates/home/contact.html
{% extends "home/home.html" %}

{% block content %}

<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h3>CONTACT INFO</h3>
        <h4>学校</h4>
        <p>
          广东科技学院<br>
          电子邮件：whfoxxx1999@163.com
        </p>

        <br>
        <h4>项目地址</h4>
        <p>
          GitHub：https://github.com/whf15/Flask-TravelWeb<br>
          电子邮件：whfoxxx1999@163.com
        </p>
        <br>
        <h4>班级姓名</h4>
        <p>
          班级：18级软件工程创新班<br>
          姓名：吴昊锋
        </p>
      </div>
      <div class="col-sm-6">
        <h3>意见建议</h3>
        <div id="note"></div>
        <div id="fields">
        {% for msg in get_flashed_messages(category_filter=["ok"]) %}
            <div class="alert alert-success alert-dismissible">
                <h4><i class="icon fa fa-check"></i> 操作成功</h4>
                {{ msg }}
            </div>
        {% endfor %}
          <form id="ajax-contact-form" class="form-horizontal" action="" method="post" >
            <div class="form-group">
                <label>{{ form.name.lable}}</label>
                {{ form.name }}
                {% for err in form.name.errors %}
                    <div class="notification_error">{{ err }}</div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label >{{ form.email.label }}</label>
                {{ form.email }}
                {% for err in form.email.errors %}
                    <div class="notification_error">{{ err }}</div>
                {% endfor %}
            </div>
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                    <label >{{ form.content.label }}</label>
                    {{ form.content }}
                    {% for err in form.content.errors %}
                    <div class="notification_error">{{ err }}</div>
                {% endfor %}
                </div>
              </div>
            </div>
                {{ form.csrf_token }}
                {{ form.submit }}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

app/templates/home/index.html
{% extends "home/home.html" %}

{% block content %}
<!--导入幻灯-->
{% include "home/slide.html" %}
<div id="front_tabs">
  <div class="container">
    <div class="tabs_wrapper tabs1_wrapper">
      <div class="tabs tabs1">
        <div class="tabs_tabs tabs1_tabs">
            <ul>
              <li class="active flights"><a href="#tabs-1">Flights</a></li>
            </ul>
        </div>
        <div class="tabs_content tabs1_content">
            <div id="tabs-1">
                <!--导入搜素框-->
                {% include "home/search_box.html" %}
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="popular_cruises1">
  <div class="container">
    <h2 class="animated">热门景区</h2>
    <br><br>
    <div id="popular_wrapper" class="animated" data-animation="fadeIn" data-animation-delay="300">
      <div id="popular_inner">
          <div id="popular">
              <div class="carousel-box">
                <div class="inner">
                  <div class="carousel main">
                    <ul>
                      {% for v in scenic %}
                      <li>
                        <div class="popular">
                          <div class="popular_inner">
                            <figure>
                              <img src="{{url_for('static',filename='uploads/'+v.logo)}}" alt="" class="img-responsive">
                              <div class="over">
                                <div class="v1">{{v.title}}<span>{{v.area.name}}</span></div>
                                <div class="v2">{{v.introduction.replace(v.introduction[100:],'...')}}</div>
                              </div>
                            </figure>
                            <div class="caption">
                              <div class="txt1"><span>{{v.title}}</span> {{v.area.name}}</div>
                              <div class="txt2">{{v.address}}</div>
                              <div class="txt3 clearfix">
                              <div class="stars1">
                                    {% for i in range(5) %}
                                      {% if i < v.star %}
                                        <img src="{{url_for('static',filename='base/images/star1.png')}}" alt="">    
                                      {% else %}
                                        <img src="{{url_for('static',filename='base/images/star2.png')}}" alt="">
                                      {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="right_side"><a href="{{url_for('home.info',id=v.id)}}" class="btn-default btn1">查看</a></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="popular_pagination"></div>
          </div>
      </div>
    </div>
  </div>
</div>


{% for v in hot_area %} 
<div id="team1">
  <div class="container">
    <h2 class="animated">{{ v.name }}</h2>
    <div class="title1 animated">{{v.introduction}}</div>
    <br>
    <div class="row">
      {% for vv in v.scenic %}
      <div class="col-sm-4">
        <div class="thumb3 animated" data-animation="flipInY" data-animation-delay="300">
          <div class="thumbnail clearfix">
            <figure class="">
              <a href="{{url_for('home.info',id=vv.id)}}">
              <img src="{{url_for('static',filename='uploads/'+vv.logo)}}" alt="" class="img-responsive">
              <div class="over">{{vv.title}}</div>
              </a>
            </figure>
            <div class="caption">
              <div class="txt1">{{vv.title}}</div>
              <div class="txt2">{{vv.address}}</div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
</div>
{% endfor %}


{% endblock %}

app/templates/home/info.html
{% extends "home/home.html" %}
{% block content %}
<div>
    <img src="{{url_for('static',filename='base/images/about_banner.jpg')}}">
</div>
<div class="breadcrumbs1_wrapper">
  <div class="container">
    <div class="breadcrumbs1"><a href="/">首页</a><span>/</span>景区详情</div>
  </div>
</div>

<!--景区内容-->
<div id="team1">
  <div class="container">
    <h2 class="animated">{{scenic.title}}
      {% if count %} 
        <button class="collect-button">已收藏</button>
      {% else %}
        <button class="collect-button">收藏</button>
      {% endif %}
    </h2>
    <div class="title1">{{scenic.content|safe}}</div>
  </div>
</div>
<!--游记列表-->
<div class="container" style="padding-bottom: 100px">
  <h2 class="animated">{{scenic.title}}游记</h2>
    <div class="row">
    {% if not scenic.travels %}
      <div class="title1">暂无游记</div>
    {% else %}
    <div class="col-sm-12 animated undefined visible">
      <ul class="ul2" style="padding-left: 150px">
        {% for v in scenic.travels %}
        <li class="form-groupe">
          <a  href="{{url_for('home.travels',id=v.id)}}">{{ v.title }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>
</div>

<script src="{{ url_for('static',filename='layer/layer.js') }}"></script>
<script>
    $(document).ready(function () {
        $(".collect-button").click(function () {       // 触发点击事件
            user_id = {{ user_id }};                   // 获取用户ID
            if(!user_id){                               // 如果用户ID不错在，即用户未登录
              layer.msg("请先登录",{icon:2,time:2000}); // layer弹出错误信息
              return false;                             // 终止执行
            }
            var scenic_id = {{ scenic.id }};            // 获取景区ID
            $.ajax({                                    // 使用Ajax异步提交
                url: "{{ url_for('home.collect_add') }}", // 提交到的URL
                type: "GET",                            // 提交方式为GET
                data:{scenic_id: scenic_id},            // 传递参数
                dataType: "json",                       // 数据类型为json
                success: function (res) {               // 操作成功后执行逻辑
                    if (res.ok == 1) {
                        layer.msg("收藏成功！",{icon:1,time:2000}); // 显示弹出层信息
                        $(".collect-button").empty();               // 清空按钮区文字
                        $(".collect-button").append("已收藏");      // 填充文字
                    } else {
                        layer.msg("您已收藏",{icon:2,time:2000});   // 提示已收藏
                    }
                }
            })
        });
    });
</script>

{% endblock %}

app/templates/home/search.html
{% extends "home/home.html" %}
{% import "common/home_page.html" as pg %}
{% block content %}
<div id="main">
<div id="content">
  <div class="container">
    <div class="tabs_wrapper tabs1_wrapper">
      <div class="tabs tabs2">
        <div class="tabs_content tabs1_content">
            <div id="tabs-1">
              {% include "home/search_box.html" %}
              <div class="row">
                <div class="col-sm-12">
                  {% if not page_data.items %}
                    <div class="txt1" style="padding: 20px;color:red">
                      没有符合条件的景区，请重新查询
                    </div>
                  {% else %}
                  <div class="row">
                    {% for v in page_data.items %}
                    <div class="col-sm-4">
                      <div class="thumb4">
                        <div class="thumbnail clearfix">
                          <figure>
                            <img src="{{url_for('static',filename='uploads/'+ v.logo)}}" height='240px' class="img-responsive">
                          </figure>    
                          <div class="caption">
                            <div class="txt1">{{ v.title }}</div>
                            <div class="txt3 clearfix">
                              <div class="left_side">
                                <div class="nums">{{ v.address }}</div>
                              </div>
                              <div class="right_side"><a href="{{url_for('home.info',id=v.id)}}" class="btn-default btn1">查看</a></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="page" style="text-align: center;">
      {{ pg.page(page_data,'home.search') }}
    </div>
  </div>
</div>

{% endblock %}

app/templates/home/travels.html
{% extends "home/home.html" %}
{% block content %}
<div>
    <img width=100% height=270px  src="{{url_for('static',filename='base/images/gonglue_banner.jpg')}}">
</div>


<div class="breadcrumbs1_wrapper">
  <div class="container">
    <div class="breadcrumbs1">
      <a href="/">首页</a>
      <span>/</span>
      <a href="{{url_for('home.info',id=travels.scenic_id)}}">景区</a>
      <span>/</span>游记
    </div>
  </div>
</div>

<div id="team1">
  <div class="container">
    <h2 class="animated">{{travels.title}}</h2>
    <div class="title1">作者：{{ travels.author }} &nbsp&nbsp&nbsp{{ travels.addtime }}</div>
    <div class="content">{{travels.content|safe}}</div>
  </div>
</div>
{% endblock %}